import { FileText, FileSpreadsheet, Calendar, User, Eye, Trash2, LayoutList, Database, Download } from 'lucide-react';
import { cn } from '../../../../lib/utils';

interface ReportsTableProps {
  reports: any[];
  isLoading: boolean;
  onView: (report: any) => void;
  onDelete?: (id: number) => void;
  onDownload: (report: any) => void;
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  indexOfFirstItem: number;
  indexOfLastItem: number;
}

const STATUS_STYLES: Record<string, string> = {
  Published: 'bg-emerald-50 text-emerald-600 border-emerald-100 dark:bg-emerald-500/10 dark:text-emerald-400 dark:border-emerald-500/20',
  'Pending Review': 'bg-amber-50 text-amber-600 border-amber-100 dark:bg-amber-500/10 dark:text-amber-400 dark:border-amber-500/20',
  Draft: 'bg-gray-100 text-gray-500 border-gray-200 dark:bg-slate-800 dark:text-slate-400 dark:border-slate-700',
};

const TYPE_STYLES: Record<string, string> = {
  Production: 'bg-emerald-50 text-emerald-700 border-emerald-100 dark:bg-emerald-500/10 dark:text-emerald-400',
  Fishery: 'bg-blue-50 text-blue-700 border-blue-100 dark:bg-blue-500/10 dark:text-blue-400',
  Financial: 'bg-violet-50 text-violet-700 border-violet-100 dark:bg-violet-500/10 dark:text-violet-400',
  Census: 'bg-rose-50 text-rose-700 border-rose-100 dark:bg-rose-500/10 dark:text-rose-400',
  Inventory: 'bg-cyan-50 text-cyan-700 border-cyan-100 dark:bg-cyan-500/10 dark:text-cyan-400',
};

const formatDate = (dateString: string) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
};

export default function ReportsTable({
  reports, isLoading,
  onView, onDelete, onDownload,
  currentPage, totalPages, onPageChange, indexOfFirstItem, indexOfLastItem,
}: ReportsTableProps) {
  const currentItems = reports.slice(indexOfFirstItem, indexOfLastItem);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3 ml-2 animate-in fade-in slide-in-from-left-4 duration-500">
        <div className="h-10 w-10 rounded-xl flex items-center justify-center shadow-sm border bg-primary/10 text-primary border-primary/10">
          <LayoutList size={20} />
        </div>
        <div>
          <p className="text-[10px] font-black uppercase tracking-[0.3em] leading-none mb-1 text-primary">Report Management</p>
          <h3 className="text-base font-black text-gray-800 dark:text-white uppercase tracking-tighter">
            List of <span className="italic text-primary">Reports</span>
          </h3>
        </div>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-[2rem] border border-gray-100 dark:border-slate-800 shadow-sm overflow-hidden relative">
        {isLoading && (
          <div className="absolute top-0 left-0 w-full h-1 bg-primary/10 overflow-hidden z-30">
            <div className="h-full bg-primary w-[40%] animate-progress-loop" />
          </div>
        )}

        <div className="overflow-x-auto overflow-y-auto max-h-[60vh] custom-scrollbar">
          <table className="w-full text-left border-collapse min-w-225">
            <thead className="sticky top-0 z-10 bg-gray-50/95 dark:bg-slate-800/95 border-b border-gray-100 dark:border-slate-800 backdrop-blur-sm">
              <tr className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                <th className="px-8 py-5">Report Details</th>
                <th className="px-8 py-5">Classification</th>
                <th className="px-8 py-5">Period Covered</th>
                <th className="px-8 py-5">Generated By</th>
                <th className="px-8 py-5 text-center">Status</th>
                <th className="px-8 py-5 text-right">{onDelete ? 'Actions' : 'View'}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50 dark:divide-slate-800">
              {isLoading ? (
                Array.from({ length: 5 }).map((_, idx) => (
                  <tr key={`skeleton-${idx}`} className="animate-pulse bg-white dark:bg-slate-900">
                    <td className="px-8 py-6">
                      <div className="flex items-start gap-4">
                        <div className="w-10 h-10 rounded-xl bg-gray-200 dark:bg-slate-700 shrink-0" />
                        <div className="space-y-2 w-full mt-1">
                          <div className="h-3.5 bg-gray-200 dark:bg-slate-700 rounded w-3/4" />
                          <div className="h-2.5 bg-gray-100 dark:bg-slate-800 rounded w-1/2" />
                        </div>
                      </div>
                    </td>
                    <td className="px-8 py-6"><div className="h-5 bg-gray-200 dark:bg-slate-700 rounded w-24" /></td>
                    <td className="px-8 py-6"><div className="h-4 bg-gray-200 dark:bg-slate-700 rounded w-40" /></td>
                    <td className="px-8 py-6"><div className="h-4 bg-gray-200 dark:bg-slate-700 rounded w-28" /></td>
                    <td className="px-8 py-6"><div className="flex justify-center"><div className="w-20 h-5 bg-gray-200 dark:bg-slate-700 rounded-full" /></div></td>
                    <td className="px-8 py-6 text-right"><div className="flex items-center justify-end gap-2"><div className="w-8 h-8 bg-gray-200 dark:bg-slate-700 rounded-xl" /></div></td>
                  </tr>
                ))
              ) : currentItems.length > 0 ? (
                currentItems.map((rep) => (
                  <tr key={rep.id} className="group hover:bg-gray-50/50 dark:hover:bg-slate-800/30 transition-all">

                    {/* REPORT DETAILS */}
                    <td className="px-8 py-6 align-middle">
                      <div className="flex items-center gap-4">
                        <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 border transition-all bg-primary/10 text-primary border-primary/5 group-hover:bg-primary group-hover:text-white">
                          {rep.format === 'PDF' ? <FileText size={18} /> : <FileSpreadsheet size={18} />}
                        </div>
                        <div>
                          <p className="text-sm font-black text-gray-800 dark:text-slate-200 uppercase tracking-tight">{rep.title}</p>
                          <div className="flex items-center gap-1.5 mt-0.5">
                            {rep.format === 'PDF'
                              ? <FileText size={11} className="text-red-400" />
                              : <FileSpreadsheet size={11} className="text-emerald-500" />}
                            <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">{rep.format}</span>
                            <span className="text-gray-200 dark:text-slate-700">·</span>
                            <span className="text-[10px] font-bold text-gray-400 uppercase">{rep.module}</span>
                          </div>
                        </div>
                      </div>
                    </td>

                    {/* CLASSIFICATION */}
                    <td className="px-8 py-6 align-middle">
                      <span className={cn('px-3 py-1.5 text-[9px] font-black uppercase rounded-lg border tracking-wider', TYPE_STYLES[rep.type] || 'bg-primary/5 text-primary border-primary/10')}>
                        {rep.type}
                      </span>
                    </td>

                    {/* PERIOD */}
                    <td className="px-8 py-6 align-middle">
                      <div className="flex items-center gap-2 text-[10px] font-bold text-gray-500 dark:text-slate-400 uppercase tracking-tighter">
                        <Calendar size={13} className="text-gray-400 shrink-0" />
                        <span>{formatDate(rep.period_from)}</span>
                        <span className="text-gray-300 dark:text-slate-600">–</span>
                        <span>{formatDate(rep.period_to)}</span>
                      </div>
                    </td>

                    {/* GENERATED BY */}
                    <td className="px-8 py-6 align-middle">
                      <div className="flex items-center gap-2">
                        <User size={13} className="text-gray-400 shrink-0" />
                        <div>
                          <p className="text-xs font-bold text-gray-600 dark:text-slate-300 uppercase">{rep.generated_by}</p>
                          <p className="text-[10px] font-bold text-gray-400 mt-0.5">{formatDate(rep.generated_at)}</p>
                        </div>
                      </div>
                    </td>

                    {/* STATUS */}
                    <td className="px-8 py-6 align-middle text-center">
                      <span className={cn('px-3 py-1.5 text-[9px] font-black uppercase tracking-widest rounded-md border', STATUS_STYLES[rep.status] || STATUS_STYLES.Draft)}>
                        {rep.status}
                      </span>
                    </td>

                    {/* ACTIONS */}
                    <td className="px-8 py-6 align-middle text-right">
                      <div className="flex items-center justify-end gap-1">
                        <button type="button" onClick={() => onView(rep)} title="View Report" className="p-2.5 text-slate-400 hover:text-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl transition-all cursor-pointer">
                          <Eye size={16} />
                        </button>
                        <button type="button" onClick={() => onDownload(rep)} title="Download Report" className="p-2.5 text-gray-400 hover:text-primary hover:bg-primary/10 rounded-xl transition-all cursor-pointer">
                          <Download size={16} />
                        </button>
                        {onDelete && <button type="button" onClick={() => onDelete(rep.id)} title="Delete Report" className="p-2.5 text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 rounded-xl transition-all cursor-pointer">
                          <Trash2 size={16} />
                        </button>}
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={6} className="py-32 text-center">
                    <div className="flex flex-col items-center justify-center space-y-3">
                      <div className="p-4 bg-gray-50 dark:bg-slate-800/50 rounded-full text-gray-300 dark:text-slate-700">
                        <Database size={40} strokeWidth={1} />
                      </div>
                      <div className="space-y-1">
                        <p className="text-sm font-black text-gray-500 dark:text-slate-400 uppercase tracking-tighter">No Reports Found</p>
                        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Try adjusting your filters</p>
                      </div>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* PAGINATOR */}
        <div className="p-6 border-t border-gray-100 dark:border-slate-800 flex items-center justify-between bg-gray-50/30 dark:bg-slate-900/50 shrink-0">
          <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">
            Showing{' '}
            <span className="text-gray-700 dark:text-slate-300 font-black">{reports.length > 0 ? indexOfFirstItem + 1 : 0}</span>
            {' '}to{' '}
            <span className="text-gray-700 dark:text-slate-300 font-black">{Math.min(indexOfLastItem, reports.length)}</span>
            {' '}of{' '}
            <span className="text-primary font-black">{reports.length}</span> Entries
          </p>
          <div className="flex items-center gap-1.5">
            <button disabled={currentPage === 1 || isLoading} onClick={() => onPageChange(currentPage - 1)} className="px-4 py-2 bg-white dark:bg-slate-800 border border-gray-200 text-gray-500 rounded-xl text-[10px] font-black uppercase hover:text-primary transition-all disabled:opacity-30 shadow-sm cursor-pointer">Prev</button>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map((pageNum) => (
              <button key={pageNum} onClick={() => onPageChange(pageNum)} className={cn('w-8 h-8 rounded-xl text-[11px] font-black transition-all shadow-sm border cursor-pointer', currentPage === pageNum ? 'bg-primary border-primary text-white scale-105' : 'bg-white dark:bg-slate-800 border-gray-200 text-gray-500 hover:border-primary/30 hover:text-primary')}>
                {pageNum}
              </button>
            ))}
            <button disabled={currentPage >= totalPages || totalPages === 0 || isLoading} onClick={() => onPageChange(currentPage + 1)} className="px-4 py-2 bg-white dark:bg-slate-800 border border-gray-200 text-gray-500 rounded-xl text-[10px] font-black uppercase hover:text-primary transition-all disabled:opacity-30 shadow-sm cursor-pointer">Next</button>
          </div>
        </div>
      </div>
    </div>
  );
}
