<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, DejaVu Sans, sans-serif; font-size: 10px; color: #1a1a1a; padding: 24px; }

  .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #2D6A4F; padding-bottom: 12px; }
  .header .agency { font-size: 11px; font-weight: bold; color: #2D6A4F; text-transform: uppercase; letter-spacing: 1px; }
  .header .title  { font-size: 15px; font-weight: bold; text-transform: uppercase; margin: 4px 0; }
  .header .meta   { font-size: 9px; color: #555; }

  table { width: 100%; border-collapse: collapse; margin-top: 14px; }
  thead tr { background-color: #2D6A4F; color: #fff; }
  th { padding: 7px 8px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
  tr:nth-child(even) td { background-color: #f9fafb; }

  .totals-row td { font-weight: bold; border-top: 2px solid #2D6A4F; background: #f0fdf4; }

  .footer { margin-top: 24px; font-size: 9px; color: #888; display: flex; justify-content: space-between; }
  .no-data { text-align: center; padding: 24px; color: #888; font-style: italic; }
  .summary { margin-top: 12px; font-size: 9px; color: #555; }
  .nursery-matrix-table { border-collapse: collapse; width: 100%; table-layout: auto; margin-top: 14px; }
  .nursery-matrix-table th, .nursery-matrix-table td { border: 1px solid #d1d5db; vertical-align: middle; }
  .act-header   { text-align: left; font-weight: bold; font-size: 9pt; background: #2D6A4F; color: #fff; min-width: 155px; padding: 7px 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  .site-header  { text-align: center; font-weight: bold; font-size: 10pt; background: #2D6A4F; color: #fff; padding: 7px 9px; text-transform: uppercase; letter-spacing: 0.5px; }
  .crop-header  { text-align: center; font-weight: bold; font-size: 7.5px; background: #2D6A4F; color: #fff; min-width: 55px; word-break: break-word; padding: 6px 4px; text-transform: uppercase; }
  .total-header { text-align: center; font-weight: bold; font-size: 9pt; background: #2D6A4F; color: #fff; min-width: 55px; padding: 7px 6px; text-transform: uppercase; letter-spacing: 0.5px; }
  .act-cell   { text-align: left; font-size: 8.5px; padding: 7px 9px; }
  .num-cell   { text-align: center; font-size: 9px; padding: 6px 5px; }
  .total-cell { text-align: center; font-weight: bold; font-size: 9px; padding: 6px 5px; background: #f0fdf4; }
  .grand-row td { font-weight: bold; background: #f0fdf4; border-top: 2px solid #2D6A4F; font-size: 9px; text-align: center; padding: 7px 5px; }
  .grand-label  { text-align: left !important; padding-left: 9px !important; }
</style>
</head>
<body>
  @php
    $isNurseryProduction = $report->module === 'Nursery Production Records';
  @endphp

  <div class="header">
    <div class="agency">LGU Gingoog City &mdash; Office of the City Agriculturist</div>
    <div class="title">{{ $report->title }}</div>
    <div class="meta">
      Report Type: {{ $report->type }} &nbsp;|&nbsp;
      Module: {{ $report->module }} &nbsp;|&nbsp;
      Period: {{ $report->period_from->format('M d, Y') }} &ndash; {{ $report->period_to->format('M d, Y') }} &nbsp;|&nbsp;
      Generated by: {{ $report->generated_by }} &nbsp;|&nbsp;
      Date: {{ $report->generated_at->format('M d, Y h:i A') }}
    </div>
    @if($report->notes)
    <div class="meta" style="margin-top:4px; font-style:italic;">Notes: {{ $report->notes }}</div>
    @endif
  </div>

  @if(empty($data['rows']))
    <div class="no-data">No records found for the selected period.</div>
  @elseif($isNurseryProduction)
    @php
      $nurseryHeaders  = $data['headers'] ?? [];
      $nurseryCropCols = array_slice($nurseryHeaders, 1, -1);
      $nurseryRows     = $data['rows'] ?? [];
      $siteLabel       = strtoupper($data['site_label'] ?? 'NURSERY SITE');

      $colTotals  = array_fill(0, count($nurseryCropCols), 0.0);
      $grandTotal = 0.0;
      foreach ($nurseryRows as $row) {
          $lastIdx = count($row) - 1;
          foreach ($row as $ci => $cell) {
              $numVal = (float) str_replace(',', '', $cell);
              if ($ci >= 1 && $ci < $lastIdx) {
                  $colTotals[$ci - 1] += $numVal;
              }
              if ($ci === $lastIdx) {
                  $grandTotal += $numVal;
              }
          }
      }
      $fmtNum = fn($v) => $v > 0 ? number_format($v, fmod($v, 1.0) === 0.0 ? 0 : 2) : '';
    @endphp
    <table class="nursery-matrix-table">
      <thead>
        <tr>
          <th rowspan="2" class="act-header">ACTIVITIES</th>
          <th colspan="{{ count($nurseryCropCols) }}" class="site-header">{{ $siteLabel }}</th>
          <th rowspan="2" class="total-header">TOTAL</th>
        </tr>
        <tr>
          @foreach($nurseryCropCols as $crop)
            <th class="crop-header">{{ $crop }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach($nurseryRows as $ri => $row)
          <tr>
            @foreach($row as $ci => $cell)
              @if($ci === 0)
                <td class="act-cell">{{ ($ri + 1) . '. ' . $cell }}</td>
              @elseif($ci === count($row) - 1)
                <td class="total-cell">{{ $cell }}</td>
              @else
                <td class="num-cell">{{ $cell }}</td>
              @endif
            @endforeach
          </tr>
        @endforeach
        <tr class="grand-row">
          <td class="grand-label">TOTAL</td>
          @foreach($colTotals as $colTotal)
            <td>{{ $fmtNum($colTotal) }}</td>
          @endforeach
          <td>{{ $fmtNum($grandTotal) }}</td>
        </tr>
      </tbody>
    </table>
  @else
    <table>
      <thead>
        <tr>
          @foreach($data['headers'] as $header)
            <th>{{ $header }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach($data['rows'] as $row)
          <tr>
            @foreach($row as $cell)
              <td>{{ $cell }}</td>
            @endforeach
          </tr>
        @endforeach

        @if($report->type === 'Financial' && isset($data['total']))
          <tr class="totals-row">
            <td colspan="{{ count($data['headers']) - 2 }}"></td>
            <td>TOTAL</td>
            <td>₱ {{ number_format($data['total'], 2) }}</td>
            <td></td>
          </tr>
        @endif
      </tbody>
    </table>

    <div class="summary">Total records: {{ count($data['rows']) }}</div>
  @endif

  <div class="footer">
    <span>LGU Gingoog City Agriculture Office</span>
    <span>Generated: {{ now()->format('M d, Y h:i A') }}</span>
  </div>

</body>
</html>
