import { X, FileText, FileSpreadsheet, Calendar, User, Layers, StickyNote, Download, ExternalLink } from 'lucide-react';
import { cn } from '../../../../lib/utils';

const STATUS_STYLES: Record<string, string> = {
  Published: 'bg-emerald-50 text-emerald-600 border-emerald-100 dark:bg-emerald-500/10 dark:text-emerald-400',
  'Pending Review': 'bg-amber-50 text-amber-600 border-amber-100 dark:bg-amber-500/10 dark:text-amber-400',
  Draft: 'bg-gray-100 text-gray-500 border-gray-200 dark:bg-slate-800 dark:text-slate-400',
};

const TYPE_STYLES: Record<string, string> = {
  Production: 'bg-emerald-50 text-emerald-700 border-emerald-100 dark:bg-emerald-500/10 dark:text-emerald-400',
  Fishery: 'bg-blue-50 text-blue-700 border-blue-100 dark:bg-blue-500/10 dark:text-blue-400',
  Financial: 'bg-violet-50 text-violet-700 border-violet-100 dark:bg-violet-500/10 dark:text-violet-400',
  Census: 'bg-rose-50 text-rose-700 border-rose-100 dark:bg-rose-500/10 dark:text-rose-400',
  Inventory: 'bg-cyan-50 text-cyan-700 border-cyan-100 dark:bg-cyan-500/10 dark:text-cyan-400',
};

const formatDate = (d: string) => {
  if (!d) return 'N/A';
  return new Date(d).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
};

interface ViewReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: any;
  onDownload?: (report: any) => void;
}

const InfoRow = ({ icon, label, children }: { icon: React.ReactNode; label: string; children: React.ReactNode }) => (
  <div className="flex items-start gap-4 py-4 border-b border-gray-50 dark:border-slate-800 last:border-0">
    <div className="w-8 h-8 rounded-xl bg-gray-50 dark:bg-slate-800 flex items-center justify-center text-gray-400 shrink-0 mt-0.5">
      {icon}
    </div>
    <div className="flex-1">
      <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">{label}</p>
      <div className="text-sm font-black text-gray-800 dark:text-white">{children}</div>
    </div>
  </div>
);

export default function ViewReportModal({ isOpen, onClose, report, onDownload }: ViewReportModalProps) {
  if (!isOpen || !report) return null;
  const handleOpenFullPreview = () => {
    window.open(`/reports-preview/${report.id}`, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="fixed inset-0 z-99 flex items-center justify-center p-4" onClick={onClose}>
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm animate-in fade-in duration-300" />

      <div
        className="relative w-full max-w-4xl bg-white dark:bg-slate-900 rounded-[2.5rem] shadow-2xl border border-gray-100 dark:border-slate-800 animate-in zoom-in-95 slide-in-from-bottom-4 duration-300 overflow-hidden flex flex-col max-h-[90vh]"
        onClick={e => e.stopPropagation()}
      >
        {/* HEADER */}
        <div className="flex items-center justify-between px-8 py-6 border-b border-gray-100 dark:border-slate-800 shrink-0">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl flex items-center justify-center border bg-primary/10 text-primary border-primary/10">
              {report.format === 'PDF' ? <FileText size={22} /> : <FileSpreadsheet size={22} />}
            </div>
            <div>
              <span className={cn('text-[9px] font-black uppercase tracking-[0.3em] px-2 py-0.5 rounded-md border', TYPE_STYLES[report.type] || 'bg-primary/5 text-primary border-primary/10')}>
                {report.type}
              </span>
              <h2 className="text-lg font-black text-gray-800 dark:text-white uppercase tracking-tighter leading-tight mt-1 max-w-lg">
                {report.title}
              </h2>
            </div>
          </div>
          <button onClick={onClose} className="p-2.5 rounded-2xl text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-all cursor-pointer shrink-0">
            <X size={20} />
          </button>
        </div>

        {/* BODY */}
        <div className="flex-1 overflow-y-auto custom-scrollbar">
          <div className="px-8 py-2">
            <InfoRow icon={<Layers size={15} />} label="Data Module">
              <span className="text-xs font-bold text-gray-600 dark:text-slate-300">{report.module || 'N/A'}</span>
            </InfoRow>
            <InfoRow icon={<Calendar size={15} />} label="Period Covered">
              <div className="flex items-center gap-2 text-xs font-bold text-gray-600 dark:text-slate-300">
                <span>{formatDate(report.period_from)}</span>
                <span className="text-gray-300 dark:text-slate-600">–</span>
                <span>{formatDate(report.period_to)}</span>
              </div>
            </InfoRow>
            <InfoRow icon={<User size={15} />} label="Generated By">
              <p className="text-xs font-bold text-gray-600 dark:text-slate-300 uppercase">{report.generated_by}</p>
              <p className="text-[10px] font-bold text-gray-400 mt-0.5">{formatDate(report.generated_at)}</p>
            </InfoRow>
            <InfoRow icon={report.format === 'PDF' ? <FileText size={15} /> : <FileSpreadsheet size={15} />} label="Output Format">
              {report.format === 'PDF'
                ? <span className="flex items-center gap-1.5 text-red-500 text-xs font-black uppercase"><FileText size={13} /> PDF Document</span>
                : <span className="flex items-center gap-1.5 text-emerald-600 text-xs font-black uppercase"><FileSpreadsheet size={13} /> Excel Spreadsheet</span>}
            </InfoRow>
            <InfoRow icon={<span className="text-[10px] font-black leading-none">●</span>} label="Status">
              <span className={cn('px-3 py-1.5 text-[9px] font-black uppercase tracking-widest rounded-md border', STATUS_STYLES[report.status] || STATUS_STYLES.Draft)}>
                {report.status}
              </span>
            </InfoRow>
            {report.notes && (
              <InfoRow icon={<StickyNote size={15} />} label="Notes / Remarks">
                <p className="text-xs font-bold text-gray-600 dark:text-slate-300 leading-relaxed whitespace-pre-wrap">{report.notes}</p>
              </InfoRow>
            )}
          </div>
        </div>

        {/* FOOTER */}
        <div className="flex items-center justify-end gap-3 px-8 py-5 border-t border-gray-100 dark:border-slate-800 bg-gray-50/50 dark:bg-slate-900/50 shrink-0">
          <button
            type="button"
            onClick={handleOpenFullPreview}
            className="flex items-center gap-2 px-5 py-3 rounded-2xl text-xs font-black uppercase tracking-widest text-primary border border-primary/20 bg-primary/5 hover:bg-primary/10 transition-all cursor-pointer"
          >
            <ExternalLink size={14} />
            Data Preview
          </button>
          <button
            type="button"
            onClick={() => onDownload && onDownload(report)}
            className="flex items-center gap-2 px-8 py-3 rounded-2xl text-xs font-black uppercase tracking-widest transition-all shadow-xl shadow-primary/20 active:scale-95 bg-primary hover:opacity-90 text-white cursor-pointer"
            title={`Download ${report.format}`}
          >
            <Download size={15} />
            Download {report.format}
          </button>
        </div>
      </div>
    </div>
  );
}
